---
http:
    endpoint: 0.0.0.0:8094
log:
    # logs might either go to stderr or to file with rotation
    destination: stderr
    # destination: file
    # filename: /var/log/aos/bg-scheduler.log
    # max_size: 200 # in MB
    # max_age: 0 # in days
    # max_backups: 10 # number of files to keep
shutdown:
    sleep: 0s
